---
- name: apt-get install devel packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - zlib1g-dev
    - libbz2-dev
    - libssl-dev
    - libreadline-dev
    - libncurses5-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libdb-dev
    - libexpat-dev
    - libpcap-dev
    - liblzma-dev
    - libpcre3-dev

